import { describe, it, expect } from 'vitest';
import { isSvg, stripSvg, applySvgStripping } from '../strip-svg';

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

/** Encodes a string as an ArrayBuffer (UTF-8). */
function toBuffer(s: string): ArrayBuffer {
  return new TextEncoder().encode(s).buffer;
}

/** Decodes an ArrayBuffer to a string (UTF-8). */
function fromBuffer(buf: ArrayBuffer): string {
  return new TextDecoder().decode(buf);
}

// ---------------------------------------------------------------------------
// isSvg
// ---------------------------------------------------------------------------

describe('isSvg', () => {
  it('returns true for a buffer starting with <svg', () => {
    expect(isSvg(toBuffer('<svg xmlns="http://www.w3.org/2000/svg"></svg>'))).toBe(true);
  });

  it('returns true for a buffer starting with <?xml', () => {
    const svg = '<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg"></svg>';
    expect(isSvg(toBuffer(svg))).toBe(true);
  });

  it('returns true for SVG with leading whitespace', () => {
    expect(isSvg(toBuffer('  \n  <svg xmlns="http://www.w3.org/2000/svg"></svg>'))).toBe(true);
  });

  it('returns false for a JPEG buffer', () => {
    const jpeg = new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10]);
    expect(isSvg(jpeg.buffer)).toBe(false);
  });

  it('returns false for a PNG buffer', () => {
    const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    expect(isSvg(png.buffer)).toBe(false);
  });

  it('returns false for an empty buffer', () => {
    expect(isSvg(new ArrayBuffer(0))).toBe(false);
  });

  it('returns false for plain text that is not SVG', () => {
    expect(isSvg(toBuffer('Hello, world!'))).toBe(false);
  });

  it('returns false for HTML that starts with <!DOCTYPE>', () => {
    expect(isSvg(toBuffer('<!DOCTYPE html><html></html>'))).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// stripSvg — metadata element removal
// ---------------------------------------------------------------------------

describe('stripSvg – removes <metadata> elements', () => {
  it('removes a <metadata> block', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <metadata>
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:creator>Jane Doe</dc:creator>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <rect width="100" height="100"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<metadata>');
    expect(result).not.toContain('dc:creator');
    expect(result).not.toContain('Jane Doe');
    expect(result).toContain('<rect');
  });

  it('removes multiline metadata block', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <metadata id="meta">
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <cc:Work><dc:title>My Drawing</dc:title></cc:Work>
    </rdf:RDF>
  </metadata>
  <circle cx="50" cy="50" r="40"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<metadata');
    expect(result).not.toContain('My Drawing');
    expect(result).toContain('<circle');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — <desc> and <title> removal
// ---------------------------------------------------------------------------

describe('stripSvg – removes <desc> and <title> elements', () => {
  it('removes <desc> element', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <desc>Created by Inkscape 1.2</desc>
  <rect width="50" height="50"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<desc>');
    expect(result).not.toContain('Created by Inkscape');
    expect(result).toContain('<rect');
  });

  it('removes <title> element', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <title>Author: Jane, 2024</title>
  <path d="M0 0 L100 100"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<title>');
    expect(result).not.toContain('Author: Jane');
    expect(result).toContain('<path');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — XML comment removal
// ---------------------------------------------------------------------------

describe('stripSvg – removes XML comments', () => {
  it('removes a single-line comment', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by Adobe Illustrator 2023 -->
  <rect width="100" height="100"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<!--');
    expect(result).not.toContain('Adobe Illustrator');
    expect(result).toContain('<rect');
  });

  it('removes a multiline comment', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <!--
    Copyright 2024 Jane Doe
    Licensed under CC-BY 4.0
  -->
  <circle cx="50" cy="50" r="40"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<!--');
    expect(result).not.toContain('Copyright');
    expect(result).toContain('<circle');
  });

  it('removes multiple comments', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- comment 1 -->
  <rect width="10" height="10"/>
  <!-- comment 2 -->
  <circle cx="5" cy="5" r="5"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<!--');
    expect(result).toContain('<rect');
    expect(result).toContain('<circle');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — processing instruction removal
// ---------------------------------------------------------------------------

describe('stripSvg – removes processing instructions (except <?xml)', () => {
  it('removes non-xml processing instructions', () => {
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<?inkscape export-filename="output.svg"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <rect width="100" height="100"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('<?inkscape');
    expect(result).toContain('<?xml');
    expect(result).toContain('<rect');
  });

  it('preserves <?xml declaration', () => {
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="M0 0"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('<?xml');
    expect(result).toContain('<path');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — namespace attribute removal
// ---------------------------------------------------------------------------

describe('stripSvg – removes Inkscape/Sodipodi/RDF namespace declarations', () => {
  it('removes inkscape namespace declaration', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.0.dtd"
     width="100" height="100">
  <rect width="50" height="50"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('xmlns:inkscape');
    expect(result).not.toContain('xmlns:sodipodi');
    expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(result).toContain('width="100"');
    expect(result).toContain('<rect');
  });

  it('removes dc/cc/rdf namespace declarations', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:cc="http://creativecommons.org/ns#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <circle cx="50" cy="50" r="40"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('xmlns:dc');
    expect(result).not.toContain('xmlns:cc');
    expect(result).not.toContain('xmlns:rdf');
    expect(result).toContain('<circle');
  });

  it('removes inkscape: attributes on elements', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <g inkscape:label="Layer 1" inkscape:groupmode="layer" id="layer1">
    <rect width="100" height="100"/>
  </g>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('inkscape:label');
    expect(result).not.toContain('inkscape:groupmode');
    expect(result).toContain('id="layer1"');
    expect(result).toContain('<rect');
  });

  it('removes sodipodi: attributes on elements', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <path sodipodi:nodetypes="ccc" d="M0 0 L100 100"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).not.toContain('sodipodi:nodetypes');
    expect(result).toContain('d="M0 0 L100 100"');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — visual element preservation
// ---------------------------------------------------------------------------

describe('stripSvg – preserves visual elements', () => {
  it('preserves <svg> root element with viewBox and dimensions', () => {
    const svg = `<!-- Author info -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" width="200" height="200">
  <rect x="10" y="10" width="180" height="180" fill="blue"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('viewBox="0 0 200 200"');
    expect(result).toContain('width="200"');
    expect(result).toContain('height="200"');
    expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
  });

  it('preserves <defs>, <style>, gradients, and filters', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- strip me -->
  <defs>
    <linearGradient id="grad1">
      <stop offset="0%" stop-color="red"/>
      <stop offset="100%" stop-color="blue"/>
    </linearGradient>
    <filter id="blur">
      <feGaussianBlur stdDeviation="3"/>
    </filter>
    <style>.icon { fill: #333; }</style>
  </defs>
  <rect width="100" height="100" fill="url(#grad1)"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('<defs>');
    expect(result).toContain('<linearGradient');
    expect(result).toContain('<filter');
    expect(result).toContain('<style>');
    expect(result).toContain('.icon { fill: #333; }');
    expect(result).toContain('url(#grad1)');
    expect(result).not.toContain('<!--');
  });

  it('preserves <animate> and <animateTransform> elements', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- animation -->
  <circle cx="50" cy="50" r="40">
    <animate attributeName="r" from="40" to="10" dur="1s" repeatCount="indefinite"/>
    <animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="2s" repeatCount="indefinite"/>
  </circle>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('<animate');
    expect(result).toContain('<animateTransform');
    expect(result).not.toContain('<!--');
  });

  it('preserves <use>, <symbol>, <image> elements', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <symbol id="icon"><circle cx="10" cy="10" r="10"/></symbol>
  </defs>
  <use href="#icon" x="0" y="0"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('<symbol');
    expect(result).toContain('<use');
    expect(result).toContain('href="#icon"');
  });

  it('preserves CSS class attributes and ids', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg">
  <g class="layer" id="main-layer">
    <path class="shape" d="M10 10 L90 10" id="line1"/>
  </g>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('class="layer"');
    expect(result).toContain('id="main-layer"');
    expect(result).toContain('class="shape"');
    expect(result).toContain('id="line1"');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — comprehensive scenario
// ---------------------------------------------------------------------------

describe('stripSvg – comprehensive metadata stripping', () => {
  it('strips all metadata while preserving visual content', () => {
    const svg = `<?xml version="1.0" encoding="UTF-8"?>
<?inkscape export-filename="logo.svg"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.0.dtd"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:cc="http://creativecommons.org/ns#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     viewBox="0 0 100 100" width="100" height="100">
  <title>Company Logo</title>
  <desc>Created by Inkscape 1.2.2 on 2024-01-01</desc>
  <!-- This SVG was exported from Figma -->
  <metadata>
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:creator>Jane Doe</dc:creator>
        <dc:date>2024-01-01</dc:date>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs>
    <style>.logo { fill: #0066cc; }</style>
  </defs>
  <g inkscape:label="Layer 1" inkscape:groupmode="layer" sodipodi:nodetypes="ccc">
    <circle class="logo" cx="50" cy="50" r="40"/>
    <rect x="10" y="10" width="80" height="80" fill="none" stroke="black"/>
  </g>
</svg>`;

    const result = fromBuffer(stripSvg(toBuffer(svg)));

    // Metadata stripped
    expect(result).not.toContain('<metadata');
    expect(result).not.toContain('<title>');
    expect(result).not.toContain('<desc>');
    expect(result).not.toContain('<!--');
    expect(result).not.toContain('<?inkscape');
    expect(result).not.toContain('xmlns:inkscape');
    expect(result).not.toContain('xmlns:sodipodi');
    expect(result).not.toContain('xmlns:dc');
    expect(result).not.toContain('xmlns:cc');
    expect(result).not.toContain('xmlns:rdf');
    expect(result).not.toContain('inkscape:label');
    expect(result).not.toContain('inkscape:groupmode');
    expect(result).not.toContain('sodipodi:nodetypes');
    expect(result).not.toContain('Jane Doe');
    expect(result).not.toContain('Company Logo');
    expect(result).not.toContain('Created by Inkscape');

    // Visual content preserved
    expect(result).toContain('<?xml');
    expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(result).toContain('viewBox="0 0 100 100"');
    expect(result).toContain('width="100"');
    expect(result).toContain('height="100"');
    expect(result).toContain('<defs>');
    expect(result).toContain('<style>');
    expect(result).toContain('.logo { fill: #0066cc; }');
    expect(result).toContain('<circle');
    expect(result).toContain('cx="50"');
    expect(result).toContain('<rect');
    expect(result).toContain('class="logo"');
  });
});

// ---------------------------------------------------------------------------
// stripSvg — error handling
// ---------------------------------------------------------------------------

describe('stripSvg – error handling', () => {
  it('throws on non-SVG input (JPEG magic bytes)', () => {
    const jpeg = new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46]);
    expect(() => stripSvg(jpeg.buffer)).toThrow(/not a valid SVG/i);
  });

  it('throws on empty buffer', () => {
    expect(() => stripSvg(new ArrayBuffer(0))).toThrow(/not a valid SVG/i);
  });

  it('throws on plain text that is not SVG', () => {
    expect(() => stripSvg(toBuffer('Hello world'))).toThrow(/not a valid SVG/i);
  });

  it('throws on HTML that is not SVG', () => {
    expect(() => stripSvg(toBuffer('<!DOCTYPE html><html></html>'))).toThrow(/not a valid SVG/i);
  });
});

// ---------------------------------------------------------------------------
// stripSvg — roundtrip: clean SVG passes through unchanged
// ---------------------------------------------------------------------------

describe('stripSvg – clean SVG passes through unchanged', () => {
  it('does not alter an SVG with no metadata', () => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect x="10" y="10" width="80" height="80" fill="blue"/>
  <circle cx="50" cy="50" r="30" fill="red"/>
</svg>`;
    const result = fromBuffer(stripSvg(toBuffer(svg)));
    expect(result).toContain('<rect');
    expect(result).toContain('<circle');
    expect(result).toContain('fill="blue"');
    expect(result).toContain('fill="red"');
  });
});

// ---------------------------------------------------------------------------
// applySvgStripping — unit tests on the text transform
// ---------------------------------------------------------------------------

describe('applySvgStripping – text-level transforms', () => {
  it('removes <metadata>...</metadata>', () => {
    const text = '<svg><metadata><dc:creator>Me</dc:creator></metadata><rect/></svg>';
    expect(applySvgStripping(text)).not.toContain('<metadata>');
    expect(applySvgStripping(text)).toContain('<rect/>');
  });

  it('removes <!-- comments -->', () => {
    const text = '<svg><!-- secret --><path d="M0 0"/></svg>';
    expect(applySvgStripping(text)).not.toContain('secret');
    expect(applySvgStripping(text)).toContain('<path');
  });

  it('removes inkscape: attributes', () => {
    const text = '<g inkscape:label="foo" id="g1"></g>';
    const result = applySvgStripping(text);
    expect(result).not.toContain('inkscape:label');
    expect(result).toContain('id="g1"');
  });

  it('removes xmlns:inkscape declarations', () => {
    const text = '<svg xmlns:inkscape="http://inkscape.org/">';
    expect(applySvgStripping(text)).not.toContain('xmlns:inkscape');
  });
});
