// Synthetic 8×8 image with fictional camera metadata. No personal data.
const SAMPLE =
  "/9j/4QD2RXhpZgAASUkqAAgAAAAIAA8BAgAPAAAAkAAAABABAgASAAAAfgAAABIBAwABAAAAAQAAABoBBQABAAAAbgAAABsBBQABAAAAdgAAACgBAwABAAAAAgAAABMCAwABAAAAAQAAAGmHBAABAAAAoAAAAAAAAAA4YwAA6AMAADhjAADoAwAAU3ludGhldGljIGZpeHR1cmUATWV0YVN0cmlwIFRlc3QAAAYAAJAHAAQAAAAwMjEwAZEHAAQAAAABAgMAAKAHAAQAAAAwMTAwAaADAAEAAAD//wAAAqAEAAEAAAAIAAAAA6AEAAEAAAAIAAAAAAAAAP/bAEMABgQFBgUEBgYFBgcHBggKEAoKCQkKFA4PDBAXFBgYFxQWFhodJR8aGyMcFhYgLCAjJicpKikZHy0wLSgwJSgpKP/bAEMBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/AABEIAAgACAMBIgACEQEDEQH/xAAUAAEAAAAAAAAAAAAAAAAAAAAA/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/EABUBAQEAAAAAAAAAAAAAAAAAAAEH/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AAFJH/9k=";
export function createSampleFile(): File {
  const bytes = Uint8Array.from(atob(SAMPLE), (character) =>
    character.charCodeAt(0),
  );
  return new File([bytes], "metastrip-sample.jpg", { type: "image/jpeg" });
}
